CAMINHO_FOTOS = r'\\192.168.1.249\fotos'
CAMINHO_WEB = r'\\192.168.1.249\redacao\web'
CAMINHO_MODELO_WEB = r'\\192.168.1.249\redacao\web\00 - Modelo'
CAMINHO_PAGFLIP = r'\\192.168.1.249\redacao\arte\00 Pagflip'
CAMINHO_MODELO_PAGFLIP = r'\\192.168.1.249\redacao\arte\00 Pagflip\00 - Modelo'
CAMINHO_EDD = r'\\192.168.1.249\redacao\diagramacao\edicao'
CAMINHO_MODELO_EDD = r'\\192.168.1.249\redacao\arte\01 Projeto\4 Adianto de novas edições\00 - modelo'
CAMINHO_MODELO_EDD_0 = r'\\192.168.1.249\redacao\arte\01 Projeto\4 Adianto de novas edições'
CAMINHO_PRINTS = r'\\192.168.1.249\comercial\PRINTS\00 - Auto-prints'

WAYPOINT_EMAILS = r'\\192.168.1.249\comercial\PRINTS\00 - Auto-prints'